#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
colorscheme = "gruvbox"
colorscheme_bg = "dark"
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = true
# Disable statusline separator, if you want to use other value, please
# install nerd fonts
statusline_separator = "nil"
statusline_iseparator = "bar"
buffer_index_type = 4
windows_index_type = 3
enable_tabline_filetype_icon = false
enable_statusline_mode = false
statusline_unicode = false
# Enable vim compatible mode, avoid changing origin vim key bindings
vimcompatible = true
# bootstrap_before = 'myspacevim#before'
bootstrap_after = 'myspacevim#after'

# Enable autocomplete layer
[[layers]]
name = "colorscheme"
# random_theme = true

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 15

[[layers]]
name = "lang#sh"

[[layers]]
name = 'git'

[[layers]]
name = 'lang#html'

[[layers]]
name = 'lang#javascript'

[[layers]]
name = 'sudo'

[[layers]]
name = "lang#python"
python_interpreter = '/usr/bin/python'
#python_interpreter = '/home/user/miniconda3/envs/beamdata/bin/python'

[[layers]]
name = "lang#latex"

[[custom_plugins]]
repo = "https://github.com/github/copilot.vim.git"
merged = false

[[custom_plugins]]
repo = "artanikin/vim-synthwave84"
merged = false

[[custom_plugins]]
repo='dylanaraps/wal.vim'
merged = false

[[custom_plugins]]
repo='andymass/vim-matchup'
merged = false

[[custom_plugins]]
repo='NLKNguyen/papercolor-theme'
merged = false
